### ISSUE TITLE
Add a "prismatic" symbol

### ISSUE THREAD

**Issue by bhollis** [DestinyItemManager/dim-custom-symbols#13]
No idea what it would look like, but there is clamor for it.

**Comment by lowPolySkeleton** [comment]
It's basically a combination of the light and darkness icons (which are in the font already and we should likely get those added to the picker as well as the new supers if we haven't) ![image](https://github.com/DestinyItemManager/dim-custom-symbols/assets/29002828/48ba519b-c10f-4062-bd56-a58089ad322d)

Looks like this ![image](https://github.com/DestinyItemManager/dim-custom-symbols/assets/29002828/4beed9ae-035b-4ca5-b4e5-5c5d4f4eaada)

**Comment by delphiactual** [comment]
light and dark have been added along with the rest of the things that were included in the font
![image](https://github.com/DestinyItemManager/dim-custom-symbols/assets/4798491/983a8aea-1bb7-4624-a995-7684bf01700e)
